server:
  port: 9999
spring:
  profiles:
    active: dev
  application:
    name: spring-ai-code
  ai:
    deepseek:
      api-key: ********
      chat:
        options:
          model: deepseek-chat

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ********
      model-name: deepseek-chat
      #      strict-json-schema: true
      #      response-format: json_object
      max-tokens: 8192
      log-requests: true
      log-responses: true
      max-retries: 3


